#!/bin/sh
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE $DB_NAME;
EOSQL

  #GRANT ALL PRIVILEGES ON DATABASE $PDB_NAME TO $PDB_USER;
  #CREATE USER $PDB_USER WITH PASSWORD '$PDB_PASS';

